/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-container": "#0066ff",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#021f29",
        "surface-container-high": "var(--color-surface-container-high)",
        "tertiary-fixed": "#cbe7f5",
        "error-container": "#ffdad6",
        "inverse-primary": "#b3c5ff",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "surface-container-low": "var(--color-surface-container-low)",
        "on-primary-fixed": "#001849",
        "surface": "var(--color-surface)",
        "surface-bright": "var(--color-surface)",
        "surface-dim": "var(--color-surface-dim)",
        "secondary-fixed-dim": "#ffb778",
        "on-primary-fixed-variant": "#003fa4",
        "on-tertiary-container": "#f2faff",
        "on-secondary-fixed-variant": "#6c3a00",
        "secondary-fixed": "#ffdcc1",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "outline": "var(--color-outline)",
        "on-tertiary": "#ffffff",
        "on-surface": "var(--color-on-surface)",
        "on-primary-container": "#f8f7ff",
        "surface-container": "var(--color-surface-container)",
        "on-error-container": "#93000a",
        "on-secondary-container": "#613400",
        "primary-fixed": "#dae1ff",
        "outline-variant": "var(--color-outline-variant)",
        "surface-variant": "var(--color-surface-variant)",
        "on-primary": "#ffffff",
        "surface-tint": "#0054d6",
        "secondary-container": "#fd9000",
        "tertiary-container": "#5c7682",
        "background": "var(--color-background)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "inverse-surface": "var(--color-inverse-surface)",
        "error": "#ba1a1a",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "primary": "#0050cb",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#afcbd8",
        "on-secondary-fixed": "#2e1500",
        "secondary": "#8e4e00",
        "on-background": "var(--color-on-background)",
        "tertiary": "#445d69",
        "on-tertiary-fixed-variant": "#304a55",
        "primary-fixed-dim": "#b3c5ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Inter"],
        "label": ["Inter"]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
